name = "keiba-proxydeploy"
main = "cloudflare-worker.js"
compatibility_date = "2026-07-22"
preview_urls = false

[observability]
enabled = true

[observability.logs]
enabled = true

[triggers]
crons = ["* 5-12 * * *"]
